### ISSUE TITLE
Connection to indoor unit

### ISSUE THREAD

**Issue by stenjo** [v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy#1]
Hi!
Having an air-to-water Panasonic Aquarea heatpump installed in november this year I might be interested in building on and extending what you have started here. Do you have any documentation on the protocol from the heatpump and where to connect the ESP8266 board for communication with the indoor unit?

**Comment by stenjo** [comment]
Forgot to mention: My unit is a WH-SDC09H3E5 9kW T-Cap Split - H-generation.
I do have a Wifi interface, but the system seems to be proprietary and all I have is a web page with the statistics and data.

**Comment by v-s-c-o-p-e** [comment]
hi stenjo, i have an F Version WH-MDC05f3e5.
i connected an logic analyzer (https://www.amazon.de/dp/B07K6G55WG) at the indoor remote where the cable from the heatpump unit attaches. there are 4 cables. GND, 5V, RX, TX.  Dont know if the H version is similar.  You find all the Registers of the F version here.
https://github.com/vscope/geisha_aquarea_panasonic_arduino_esp8266_proxy/blob/master/README.md

**Comment by Egyras** [comment]
Hi All, H series has 2 wires for remote, so this is not a serial connection. Cn-cnt should be used were cloud module connects.
CN-CNT	TTL UART 9600,8,E,1	
1+5V +-250mV	
2  TX
3 RX,
4 +12V +-250mV	
5 GND

 I have managed to connect and got some data.
@Vscope any hints which software to use for serial data analysis, your hex values converted to decimal are the real ones or you need to do some math?

**Comment by Egyras** [comment]
Here is request from wifi module to heat pump (H-series):
71 6c 01 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 12

Here is the answer from heat pump to wifi module:
71 c8 01 10 56 55 62 49 00 05 00 00 00 00 00 00 00 00 00 00 19 15 11 55 16 5e 55 05 09 00 00 00
00 00 00 00 00 00 80 8f 80 8a b1 71 71 97 99 00 00 00 00 00 00 00 00 00 00 00 80 85 15 8a 85 85
d0 7b 78 1f 7e 1f 1f 79 79 8d 8d 9e 96 71 8f b7 a3 7b 8f 8e 85 80 8f 8a 94 9e 8a 8a 94 9e 82 90
8b 05 65 78 c1 0b 00 00 00 00 00 00 00 00 55 55 55 21 53 15 59 05 12 12 19 00 00 00 00 00 00 00
00 e2 ce 0d 71 81 72 ce 0c 92 81 9a 00 b1 80 98 9a 32 32 9a b2 32 32 32 80 9a 99 ab 99 97 7a 80
7a 80 ff 52 01 09 1e 00 00 b9 08 1b 51 47 01 14 79 01 01 84 02 00 91 02 00 05 00 00 01 00 00 06
01 02 07 01 01 01 01 00 00 00 0f

**Comment by v-s-c-o-p-e** [comment]
looks like the serial protocoll has changed in the H version. which is obvious since the f version uses a very basic protocol. just decode the hex data and try to find numeric values you know that they shall be transmitted in the stream. like current outdoor temp, flow temperature, water set temperatures.
whats the transfer rate on the H version? still 960 baud?

**Comment by Egyras** [comment]
>           looks like the serial protocoll has changed in the H version. which is obvious since the f version uses a very basic protocol. just decode the hex data and try to find numeric values you know that they shall be transmitted in the stream. like current outdoor temp, flow temperature, water set temperatures.
> whats the transfer rate on the H version? still 960 baud?

9600 baud ,8,E,1
I will try to decode what is send from wifi module to panasonic cloud.  It can be easy and maybe give more "readable" information.

One more intersting thing is that I checked cloud portal and found such values:

o=backgroundDataInfo["0xE1"];var Mode0xE1=Mo.value
noOf=backgroundDataInfo["0xF0"];var noOfZone0xF0=noOf.value
 tank=backgroundDataInfo["0xF9"];var tankCon0xF9=tank.valu
var buffer=backgroundDataInfo["0xFA"];var bufferTank0xFA=buffer.value;var
 sol=backgroundDataInfo["0xA0"];var solar0xA0=sol.value;
ar comp=backgroundDataInfo["0x20"];var compressor0x20=comp.value;
ope=backgroundDataInfo["0x80"];var operation0x80=ope.value;

operation0x80=="0"){GLOBAL.replaceViewSettingInfo(thermoBar,"function-status-text-033")}else{if(operation0x80=="1
tankCon0xF9=="0"
bufferTank0xFA=="0
solar0xA0=="0"
Bivalent0xC4=="0"
compressor0x20=="0"
noOfZone0xF0=="1"


Maybe its just some kind internal conversion,  as I expected HEX to DEC value and there they use HEX like variable...

**Comment by v-s-c-o-p-e** [comment]
https://sigrok.org/ is an open source communication analyzer.
https://www.saleae.com/de/downloads/ is a commercial software and runs with cheap 8 channel  clones...

**Comment by Egyras** [comment]
@vscope you could try to use MQTT to send commands via your ProxyESP8266

**Comment by v-s-c-o-p-e** [comment]
when serial proxy is running i want to implement a webinterface since i dont use mqtt at the moment.
however adding an mqtt interface would not be difficult.

**Comment by Egyras** [comment]
@vscope I'am not good at writing code, can you say what can be changed in your GeishaSerialRemote.ino to get answers from a heat pump to ESP8266 serial. Output is from Hex to DEC as I understand ? Thanks for help !

**Comment by horyzeli** [comment]
> hi stenjo, i have an F Version WH-MDC05f3e5.
> i connected an logic analyzer (https://www.amazon.de/dp/B07K6G55WG) at the indoor remote where the cable from the heatpump unit attaches. there are 4 cables. GND, 5V, RX, TX. Dont know if the H version is similar. You find all the Registers of the F version here.
> https://github.com/vscope/geisha_aquarea_panasonic_arduino_esp8266_proxy/blob/master/README.md

Hi,
I have the same F generation, indoor unit: WH-SXC09F3E5, outdoor unit: WH-UX09FE5, great that I've found this topic..
Since the access of data is much more limited compared to the H generation, I'd like to get more data during its operation. Is that possible to get in contact?
I also know a person who is an expert in micro controllers and electronics, we may work together to find the solution for this machine as well..

**Comment by myfirstdatalogger** [comment]
> 
> 
> > hi stenjo, i have an F Version WH-MDC05f3e5.
> > i connected an logic analyzer (https://www.amazon.de/dp/B07K6G55WG) at the indoor remote where the cable from the heatpump unit attaches. there are 4 cables. GND, 5V, RX, TX. Dont know if the H version is similar. You find all the Registers of the F version here.
> > https://github.com/vscope/geisha_aquarea_panasonic_arduino_esp8266_proxy/blob/master/README.md
> 
> Hi,
> I have the same F generation, indoor unit: WH-SXC09F3E5, outdoor unit: WH-UX09FE5, great that I've found this topic..
> Since the access of data is much more limited compared to the H generation, I'd like to get more data during its operation. Is that possible to get in contact?
> I also know a person who is an expert in micro controllers and electronics, we may work together to find the solution for this machine as well..

I would like to participate as well.

This winter I want to develop an system that can:

1. Log power and temperatures every minute
2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
4. Gives pre-warning for deice

I am not experienced in programming. But you must set some ambitious goals ;-)

**Comment by stenjo** [comment]
Just to let you know - if you have not found it yet: There is an active project covering parts of the ambitions in this project: https://github.com/Egyras/HeishaMon
Check that one out.
I'm using https://github.com/lsochanowski/GoHeishaMon to run on my CZ-TAW1 and that works for my needs.

**Comment by horyzeli** [comment]
> Just to let you know - if you have not found it yet: There is an active project covering parts of the ambitions in this project: https://github.com/Egyras/HeishaMon
> Check that one out.
> I'm using https://github.com/lsochanowski/GoHeishaMon to run on my CZ-TAW1 and that works for my needs.

Hello,
Thank you, unfortunately that project is for H generation and not applicable for F generation which we have..
