### ISSUE TITLE
No serial communication from heatpump

### ISSUE THREAD

**Issue by myfirstdatalogger** [v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy#2]
I am using an Nodemcu 1.0 ESP8266 and trying direct connection between remote and heatpump. No level shifter. With an potentiometer I can lower the voltage to below 1 Volt (Vtop) from the transmitting Remote>Heatpump. So the 3,3 Volt from the ESP8266 should be applicable. The ESP8266 is 5 Volt tolerant so the input should also be fine.

But: it doesn't work. I get an message "swSerHeatPump Wrong Package Received0". On my oscilloscope I see one signal constant HIGH, but no data. Remote gets H76.

Normal operation without ESP8266: (first start message send from the Heatpump>Remote)
![Normal start message long timebase](https://user-images.githubusercontent.com/59177419/71379565-0ecb9300-25cc-11ea-84aa-c2d12cd09c19.jpg)
![Normal start message short timebase](https://user-images.githubusercontent.com/59177419/71379566-10955680-25cc-11ea-8946-d4d66dbfd42c.jpg)

The heatpump sends the first message when connected to the remote. When I disconnect the remote there is no data and only an high signal. How can this happen? I assumed the Heatpump wil still transmit data but no reaction from the end of the line (oscilloscope).

When connecting ESP8266 with Proxy software the heatpump also only transmits an HIGH signal, but no data.

Using Arduino 1.8.10 on Windows 10
ESP8266 libary from http://arduino.esp8266.com/stable/package_esp8266com_index.json
The program geisha_aquarea_panasonic_arduino_esp8266_proxy with the included SoftwareSerial.

What am I doing wrong?

**Comment by myfirstdatalogger** [comment]
I fixed it. Remote and heatpump was switched, I misunderstood the code. Only using receive to readout the bus, no transmit until later.

**Comment by horyzeli** [comment]
> I fixed it. Remote and heatpump was switched, I misunderstood the code. Only using receive to readout the bus, no transmit until later.

Hi,
Could you please share what you've reached with this project? Is the communication working? 
Thank you!

**Comment by myfirstdatalogger** [comment]
Communications is working, but I didn't do much after this.

This winter I want to develop an system that can:

1. Log power and temperatures every minute
2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
4. Gives pre-warning for deice

I am not experienced in programming. But you must set some ambitious goals ;-)

**Comment by horyzeli** [comment]
> Communications is working, but I didn't do much after this.
> 
> This winter I want to develop an system that can:
> 
> 1. Log power and temperatures every minute
> 2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
> 3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
> 4. Gives pre-warning for deice
> 
> I am not experienced in programming. But you must set some ambitious goals ;-)

Wow, that sounds fantastic if it can be done :-)

**Comment by horyzeli** [comment]
> Communications is working, but I didn't do much after this.
> 
> This winter I want to develop an system that can:
> 
> 1. Log power and temperatures every minute
> 2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
> 3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
> 4. Gives pre-warning for deice
> 
> I am not experienced in programming. But you must set some ambitious goals 

> Communications is working, but I didn't do much after this.
> 
> This winter I want to develop an system that can:
> 
> 1. Log power and temperatures every minute
> 2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
> 3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
> 4. Gives pre-warning for deice
> 
> I am not experienced in programming. But you must set some ambitious goals ;-)

Is it possible to chat anywhere which can be faster?

**Comment by horyzeli** [comment]
> Communications is working, but I didn't do much after this.
> 
> This winter I want to develop an system that can:
> 
> 1. Log power and temperatures every minute
> 2. Can remotely be switched on/off using ESP8266 WiFi capabilities over internet
> 3. Adjust heating curve based on an temperature sensor in de room. For example fixed 20,0 degree Celcius at DS18B20.
> 4. Gives pre-warning for deice
> 
> I am not experienced in programming. But you must set some ambitious goals ;-)

Could you please send a picture where you connect the Nodemcu with the heat pump? I have found there are more CN-NMODE connection possibilities..
